version: '3.7'
services:
  docker-manager-bot:
    build: ./
    pull_policy: build
    ports:
      - "6666:6666"
    container_name: discord-docker-manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
